### ISSUE TITLE
MATCH part of Cypher query ignored?

### ISSUE THREAD

**Issue by fhureau** [neo4j-php/Bolt#120]
**Describe the bug**
I am trying to retrieve data from my neo4j database via Laravel test commands run trough a terminal, but it seems that the MATCH part of my Cypher query is ignored

**To Reproduce**

```
$conn = new \Bolt\connection\Socket(env('NEO_DOCKER'), 7687);
$bolt = new \Bolt\Bolt($conn);
$protocol = $bolt->setProtocolVersions(3)->build();
$protocol->hello(\Bolt\helpers\Auth::basic(env('NEO_USER'), env('NEO_PASS')));   
$result = $protocol->run("MATCH (p:Personne {matr: 7007}) RETURN p.nom")->pullAll()->getResponse()->getContent();

var_dump($result);
```

`> php artisan app:test-command`
      array(2) {
        ["t_first"]=>
        int(4)
        ["fields"]=>
        array(1) {
          [0]=>
          string(5) "p.nom"
        }
      }

**Expected behavior**
Retrieve p.nom actual content in the results, not the string "p.nom"

**Desktop (please complete the following information):**
 (- OS: Win 11 pro)
 - Docker-compose configuration
 - PHP Version 8.2.6
 - Neo4j Version 3.5.35
 - Bolt Library Version 3

The connection part seems fine/does not return errors, but am I missing something in the config or querying?
Thanks

PS: an upgrade of the neo4j database is scheduled but not immediately

**Comment by stefanak-michal** [comment]
Hi. That is not a issue. You are working with low level driver and structure of returned data is a little bit different. Take look here to see how data are combined. https://github.com/stefanak-michal/neo4j-bolt-wrapper/blob/a502df781632a416a4e45784f4589ab0c709a53a/src/Neo4j.php#L88
