### ISSUE TITLE
seperated queries gives different results from queries that are run as one

### ISSUE THREAD

**Issue by ephraimlambarte** [neo4j-php/Bolt#136]
**Describe the bug**
to test this, i created 2 seperate methods in my testing class. in my first method i run the `CREATE` queries seperately then in the second method i run the `CREATE` queries as one. after running the create queries i perform a node search. the node search for 2 methods produces different results.

**To Reproduce**
```
public function test_seperate_fetches() {
      $this->graphDBModel->connect()
      ->run("CREATE (:test_node {model_id: 1})")
      ->pull();
      
      $this->graphDBModel->connect()
      ->run("CREATE (:test_node {model_id: 2})")
      ->pull();
    
      $this->graphDBModel->connect()
      ->run("CREATE (:test_node {model_id: 3})")
      ->pull();
    
      $this->graphDBModel->connect()
      ->run("CREATE (:test_node {model_id: 4})")
      ->pull();
    
      $this->graphDBModel->connect()
      ->run("
          MERGE (n:test_node {model_id: 1})
          MERGE (n2:test_node {model_id: 2})
          MERGE(n)-[:influences]->(n2)
      ")
      ->pull();
      $this->graphDBModel->connect()
      ->run("
          MERGE (n2:test_node {model_id: 2})
          MERGE (n3:test_node {model_id: 3})
          MERGE(n2)-[:influences]->(n3)")
      ->pull();
      $this->graphDBModel->connect()
      ->run("
          MERGE (n3:test_node {model_id: 3})
          MERGE (n4:test_node {model_id: 4})
          MERGE(n3)-[:influences]->(n4)
      ")
      ->pull();
    
      $protocol2 = $this->graphDBModel->connect();
      $protocol2
      ->run("MATCH (node1:test_node {model_id: 1} )-[:influences*]->(n) RETURN n")
      ->pull();
      $rows = iterator_to_array($protocol2->getResponses(), false);
    
      $this->assertEquals(count($rows), 5);
}

public function test_non_seperate_fetches() {
    $protocol = $this->graphDBModel->connect();

    $protocol->run("
        CREATE (n1:test_node {model_id: 1})
        CREATE (n2:test_node {model_id: 2})
        CREATE (n3:test_node {model_id: 3})
        CREATE (n4:test_node {model_id: 4})
        
        CREATE (n1)-[:influences]->(n2)
        CREATE (n2)-[:influences]->(n3)
        CREATE (n3)-[:influences]->(n4)
    ")
    ->pull();

    $protocol2 = $this->graphDBModel->connect();
    $protocol2
    ->run("MATCH (node1:test_node {model_id: 1} )-[:influences*]->(n) RETURN n")
    ->pull();
    $rows = iterator_to_array($protocol2->getResponses(), false);

    $this->assertEquals(count($rows), 5);
}
```

**Expected behavior**
Both method should pass the test as it should return 5 items from the results. these items are the 3 nodes, the run message and the pull message.

**Actual behaviour**
Only test_non_seperate_fetches passes the test.

**Desktop (please complete the following information):**
 - OS:  Win 11 Pro
 - PHP Version: 8.1
 - Neo4j Version: `i am using memgraph`
 - Bolt Library Version: `"stefanak-michal/bolt": "^6.1"`

**Additional context**
I am using MEMGRAPH via docker. i can also provide details about my containers if that is necessary.

**Comment by stefanak-michal** [comment]
Hi. I'm not able to run your code right now but from what I see I have question first. Your method `$this->graphDBModel->connect()` returns instance of Protocol. If you call this multiple times you will get cached instance or always a new one?

**Comment by ephraimlambarte** [comment]
it always return a new instance of protocol

**Comment by stefanak-michal** [comment]
Next thing what catched my eye are these queries

```
$this->graphDBModel->connect()
    ->run("CREATE (n:test_node {model_id: 1})-[:influences]->(n2:test_node {model_id: 2})")
    ->pull();
    $this->graphDBModel->connect()
    ->run("CREATE (n:test_node {model_id: 2})-[:influences]->(n2:test_node {model_id: 3})")
    ->pull();
    $this->graphDBModel->connect()
    ->run("CREATE (n:test_node {model_id: 3})-[:influences]->(n2:test_node {model_id: 4})")
    ->pull();
```

With CREATE you create new nodes with model_id 1, 2, 3 and 4. You will not reuse the original ones you already created. So you will not create chain of nodes but just pairs.

**Comment by ephraimlambarte** [comment]
my bad. its supposed to be MERGE, i editted the code.

even with merge it produces inconsistent results

**Comment by ephraimlambarte** [comment]
![image](https://github.com/neo4j-php/Bolt/assets/21136639/49999bf5-3f09-45ea-af2d-67206eb34d61)

**Comment by stefanak-michal** [comment]
```
$protocol2
    ->run("MATCH (node1:test_node {model_id: 1} )-[:influences*]->(n) RETURN n")
    ->pull();
    $rows = iterator_to_array($protocol2->getResponses(), false);
```

in this case `count($rows)` is 3. Because `run` returns SUCCESS Response, `pull` returns one RECORD Response and one SUCCESS Response. So your code is correct.

One RECORD Response is because query contains `RETURN n`, so the query returns only node at the end of chain.

If your first test `test_seperate_fetches` fails, the next ones are not executed. So how do you know `test_non_seperate_fetches` works? Did you try to comment out the whole first test? Because I believe your second test will fail in the same way.

Btw `$this->assertEquals()` first parameter is expected value, second parameter is what you want to verify.

**Comment by stefanak-michal** [comment]
I should really focus on investigating what the queries really do. When I run this:

```
CREATE (:test_node {model_id: 1})
CREATE (:test_node {model_id: 2})
CREATE (:test_node {model_id: 3})
CREATE (:test_node {model_id: 4})

MERGE (:test_node {model_id: 1})-[:influences]->(:test_node {model_id: 2})
MERGE (:test_node {model_id: 2})-[:influences]->(:test_node {model_id: 3})
MERGE (:test_node {model_id: 3})-[:influences]->(:test_node {model_id: 4})
```

I end up with 10 nodes. The merge didn't work as expected. So there is 3 pairs of nodes and 4 nodes without any relationship. And for sure there is not a chain of nodes as expected.

**Comment by stefanak-michal** [comment]
You are right about second test. It does work. I wasn't sure how `[:REL*]` works, but I see it returns all nodes on the path.

**Comment by ephraimlambarte** [comment]
you are right. the merge is not working as expected as well

**Comment by ephraimlambarte** [comment]
my bad, i was using the MERGE the wrong way.. 
the query: `MERGE (:test_node {model_id: 1})-[:influences]->(:test_node {model_id: 2})`
creates a duplicate node because there is no node that has `{model_id: 1}` that is also connected to another node that has: `{model_id: 2}`...


so to fix this, i saved them in a variable like so: 
```
  MERGE (n:test_node {model_id: 1})
  MERGE (n2:test_node {model_id: 2})
  MERGE(n2)-[:influences]->(n2)
```

i updated my post.

**Comment by stefanak-michal** [comment]
I would prefer if you do MATCH and not MERGE to find those two nodes. Anyway after your update you connected n2 to n2.

**Comment by stefanak-michal** [comment]
> it always return a new instance of protocol

Also I would suggest to keep one protocol instance. Every time you create new protocol instance you are establishing new connection and that takes time. By experience of my friend is more time than we think.

But if you will be update your logic and you will keep one protocol instance, you have to consume responses every time. Right now you do `->run()->pull()` without calling getResponse(s), which lefts data in TCP buffer from server. When you close connection the buffer is discarded.

**Comment by ephraimlambarte** [comment]
but the problem is, its hard to get the response if i will use only one protocol because the getResponses also returns reponses from previous calls.

**Comment by stefanak-michal** [comment]
> but the problem is, its hard to get the response if i will use only one protocol because the getResponses also returns reponses from previous calls.

You should consume response after every call(s). That way you will avoid having something in buffer waiting to be consumed.

It is designed this way because bolt protocol offers pipelining, which means you can send multiple messages before consuming the response.

Of course it's up to you. It's just a suggestion on improvement.

**Comment by ephraimlambarte** [comment]
is there a method for flushing/consuming the response in a protocol object? im sorry, im looking at the README but i cant find any related method.

**Comment by stefanak-michal** [comment]
> is there a method for flushing/consuming the response in a protocol object? im sorry, im looking at the README but i cant find any related method.

Unfortunatelly Bolt protocol doesn't offer this functionality. Even if you call RESET all messages in buffer stays there, they just get signature IGNORED, and you still have to consume them. So the only way to achieve that (consuming buffer) is to call `iterator_to_array($protocol->getResponses(), false);`.

**Comment by ephraimlambarte** [comment]
GREAT TIP! im gonna need to fix my protocol class.

also fixing my queries worked! so the issue was with my queries and not with the protocol. Thank you for your help!!
