### ISSUE TITLE
E_WARNING:unlink(/tmp/php-bolt-analytics/analytics.1732118400.json): No such file or directory

### ISSUE THREAD

**Issue by hetao29** [neo4j-php/Bolt#149]
**Describe the bug**
No such file or directory

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - PHP Version :8.3.x
 - Neo4j Version : 5.19
 - Bolt Library Version :3.1.3

**Additional context**
```log
vendor/laudis/neo4j-php-client/src/BoltFactory.php(64)   Laudis\Neo4j\Bolt\ProtocolFactory::createProtocol("Bolt\\connection\\Socket::","Laudis\\Neo4j\\Authentication\\BasicAuth::","neo4j-php-client/2")^M
vendor/laudis/neo4j-php-client/src/Bolt/ProtocolFactory.php(35)  Bolt\Bolt::__construct("Bolt\\connection\\Socket::")^M
vendor/stefanak-michal/bolt/src/Bolt.php(33)     Bolt\Bolt::track()^M
vendor/stefanak-michal/bolt/src/Bolt.php(85)     unlink("/tmp/php-bolt-analytics/analytics.1732118400.json")^M
vendor/stefanak-michal/bolt/src/Bolt.php()       E_WARNING:unlink(/tmp/php-bolt-analytics/analytics.1732118400.json): No such file or directory
```

**Comment by stefanak-michal** [comment]
Hi.

The obvious solution would be to add `@` ..but how the file could be missing if it existed just few miliseconds ago, because it was found by `foreach (glob(sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'php-bolt-analytics' . DIRECTORY_SEPARATOR . 'analytics.*.json') as $file) {` few lines higher.

Is your `/tmp` alias? Could `realpath` help mitigate this issue?

**Comment by hetao29** [comment]
If parallel web page requests are made, track() will be executed in parallel, and if the request to api-eu.mixpanel.com takes a long time, there will be a problem of deleting the same file multiple times after glob.
And I think use is_file to check the file exists may be better。

**Comment by stefanak-michal** [comment]
Later on that day I was thinking about same thing. Therefore it's ease fix, you could have create PR yourself.

**Comment by stefanak-michal** [comment]
Thanks for reporting this problem

**Comment by hetao29** [comment]
I thank if you simply block errors, you may still not solve the potential duplicate submission problem ^_^~~~~

**Comment by stefanak-michal** [comment]
> I thank if you simply block errors, you may still not solve the potential duplicate submission problem ^_^~~~~

That is already solved with the way request is send. I though about it when I did implementation.
