### ISSUE TITLE
Issue with geolocation points

### ISSUE THREAD

**Issue by jac12498** [neo4j-php/Bolt#47]
I am using the laudis/neo4j-php-client that uses your Bolt package. I am performing a geolocation search on Neo4j of a point with a set of nodes that each define their border through a set of points. Essentially, I am doing a point-in-polygon search. To speed the search, the first step is to return the set of nodes whose bounding box (defined by a min and a max point) MAY contain the point. I do this with the following Neo4j query:

    MATCH (b:Border) WHERE b.min < point({latitude: 42.020110, longitude: -74.084010}) < b.max RETURN b;

This query works fine with the Neo4j Browser and with the laudis/neo4j-php-client using the HTTP protocol. However, with the BOLT protocol, I get the following error:

PHP Fatal error:  Uncaught Bolt\error\UnpackException: Structure call for method "unpackFloat" generated unpack error in /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php:194
Stack trace:
#0 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(170): Bolt\PackStream\v1\Unpacker->unpackSpecificStructure()
#1 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(103): Bolt\PackStream\v1\Unpacker->unpackStruct()
#2 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(328): Bolt\PackStream\v1\Unpacker->u()
#3 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(126): Bolt\PackStream\v1\Unpacker->unpackList()
#4 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(222): Bolt\PackStream\v1\Unpacker->u()
#5 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(192): Bolt\PackStream\v1\Unpacker->unpackMap()
#6 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(170): Bolt\PackStream\v1\Unpacker->unpackSpecificStructure()
#7 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(103): Bolt\PackStream\v1\Unpacker->unpackStruct()
#8 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(328): Bolt\PackStream\v1\Unpacker->u()
#9 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(126): Bolt\PackStream\v1\Unpacker->unpackList()
#10 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/PackStream/v1/Unpacker.php(79): Bolt\PackStream\v1\Unpacker->u()
#11 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/protocol/AProtocol.php(103): Bolt\PackStream\v1\Unpacker->unpack()
#12 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/protocol/V4.php(39): Bolt\protocol\AProtocol->read()
#13 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/protocol/V4.php(25): Bolt\protocol\V4->pull()
#14 /home/mydistrict/public_html/neo4j/v0.1/vendor/stefanak-michal/bolt/src/Bolt.php(274): Bolt\protocol\V4->pullAll()
#15 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php(130): Bolt\Bolt->pullAll()
#16 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php(57): Laudis\Neo4j\Network\Bolt\BoltSession->runStatements()
#17 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Client.php(54): Laudis\Neo4j\Network\Bolt\BoltSession->run()
#18 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Client.php(46): Laudis\Neo4j\Client->runStatements()
#19 /home/mydistrict/public_html/neo4j/v0.1/Application/Models/Neo4jBase.php(336): Laudis\Neo4j\Client->runStatement()
#20 /home/mydistrict/public_html/neo4j/v0.1/Application/Models/District.php(116): Model\Neo4jBase->queryMultiple()
#21 /home/mydistrict/public_html/neo4j/v0.1/tests/district_geolocation.php(22): Model\District->getByGeoLocation()
#22 {main}

Next Laudis\Neo4j\Exception\Neo4jException: Neo4j errors detected. First one with code "" and message "Structure call for method "unpackFloat" generated unpack error" in /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php:132
Stack trace:
#0 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php(57): Laudis\Neo4j\Network\Bolt\BoltSession->runStatements()
#1 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Client.php(54): Laudis\Neo4j\Network\Bolt\BoltSession->run()
#2 /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Client.php(46): Laudis\Neo4j\Client->runStatements()
#3 /home/mydistrict/public_html/neo4j/v0.1/Application/Models/Neo4jBase.php(336): Laudis\Neo4j\Client->runStatement()
#4 /home/mydistrict/public_html/neo4j/v0.1/Application/Models/District.php(116): Model\Neo4jBase->queryMultiple()
#5 /home/mydistrict/public_html/neo4j/v0.1/tests/district_geolocation.php(22): Model\District->getByGeoLocation()
#6 {main}
  thrown in /home/mydistrict/public_html/neo4j/v0.1/vendor/laudis/neo4j-php-client/src/Network/Bolt/BoltSession.php on line 132

**To Reproduce**
Execute the above Neo4j query using the laudis/neo4j-php-driver configured to use BOLT.

**Expected behavior**
Return of the nodes - does work properly with the HTTP protocol.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - PHP Version 8.0.2
 - Neo4j Version 4.1.6
 - Bolt Library Version master

**Additional context**

**Comment by jac12498** [comment]
If you want to take a look at this, I can send you the query along with the login/password to my Neo4j server so you can see it for yourself. The exact query and server works if I use the HTTP protocol instead of the BOLT protocol. My guess is that the failure has something to do with the size of the response and/or the handling of a list of points.

**Comment by stefanak-michal** [comment]
I've tried to create node with point() property:
```CREATE (t:Test { p: point({longitude: 1, latitude: 2}) })```

After I call Bolt library to receive this node with result:
```php
array (size=1)
      0 => 
        object(Bolt\structures\Node)[20]
          private 'id' => int 16
          private 'labels' => 
            array (size=1)
              0 => string 'Test' (length=4)
          private 'properties' => 
            array (size=1)
              'p' => 
                object(Bolt\structures\Point2D)[19]
                  private 'srid' => int 4326
                  private 'x' => float 1
                  private 'y' => float 2
```

Tested on Neo4j 4.2.1

What's the structure of your node `Border`?

**Comment by stefanak-michal** [comment]
no response from author
