### ISSUE TITLE
Bolt\error\ConnectException when sending large chunks of data.

### ISSUE THREAD

**Issue by transistive** [neo4j-php/Bolt#51]
**Describe the bug**
When I try to send data of around 100kb, Bolt freezes for a while and then throws a ` Bolt\error\ConnectException`. If the size is around 50kb, the driver works pretty much instantly.

**To Reproduce**
```php
$bolt = new Bolt(new StreamSocket('<host>'));
$bolt->init('MyClient/1.0', '<user>', '<password>');

$bolt->run('RETURN 1 AS x, ['content' => <Really long string of around 100kb>]);
```

**Expected behavior**
The query runs near instantly.

**Desktop (please complete the following information):**
 - OS: Linux box 5.12.0-1-MANJARO #1 SMP PREEMPT Mon Apr 26 22:09:28 UTC 2021 x86_64 GNU/Linux, but within Docker.
 - PHP Version: 7.4.18
 - Neo4j Version 4.2.5
 - Bolt Library Version v2.1

**Additional context**
I ran across this issue while working on my web crawlers. You can easily generate a text based on the number of bytes using [lorem ipsum](https://www.lipsum.com/)

**Comment by stefanak-michal** [comment]
Yes, you are right, I know about it. :D

Bolt message can be 65,535 bytes long. Which means message with string bigger size fail. Bolt have something which this driver doesn't have implemented https://7687.org/bolt/bolt-protocol-message-specification-4.html#chunking

It looks the time came to implement that.

**Comment by transistive** [comment]
Very quick response time! I reviewed it and it looks good. Can't wait to check it out!
