### ISSUE TITLE
Read error when writing big random data

### ISSUE THREAD

**Issue by transistive** [neo4j-php/Bolt#60]
**Describe the bug**
When creating parameters with random data, a standard read error appears. When testing big strings, it works flawlessly, but with big random data is crashes.

**To Reproduce**
```php
$socket = new \Bolt\connection\StreamSocket('neo4j');
$neo = new \Bolt\Bolt($socket);
$neo->init('MyClient/1.0', 'neo4j', 'test');
$neo->begin();

$neo->run('MERGE (a:label {id:"xyz"})');

$params = [
    'id' => 'xyz',
];

while (true) {
    try {
        // show current length of parameters array
        echo strlen(serialize($params)).PHP_EOL;

        $check = $neo->run('MATCH (a :label {id:$id}) RETURN a', $params);

        $params[base64_encode(random_bytes(32))] = base64_encode(random_bytes(128));
    } catch (Exception $e) {
        echo $e;

        $neo->run('MATCH (a:label {id:"xyz"}) DELETE a');

        exit;
    }
}
```

**Expected behaviour**
This script should be able to run for as long as the server or connection does not crash.

**Desktop (please complete the following information):**
 - OS: Docker version 20.10.8, build 3967b7d28e in Linux xps 5.13.13-1-MANJARO SMP PREEMPT Thu Aug 26 20:34:21 UTC 2021 x86_64 GNU/Linux
 - PHP Version PHP 8.0.7 (cli) (built: Jun  4 2021 18:34:28) ( NTS )
 - Neo4j Version: 4.3.2
 - Bolt Library Version  v2.3

**Additional context**
This problem came to light from this issue in the client: https://github.com/neo4j-php/neo4j-php-client/issues/70.

**Comment by stefanak-michal** [comment]
just a small bug :)
350f252

**Comment by stefanak-michal** [comment]
https://github.com/neo4j-php/Bolt/releases/tag/v2.5.1

**Comment by stefanak-michal** [comment]
Btw it's really dangerous piece of code. After it was working I reached a moment when my computer started freezing and Neo4j crashed at memory.

**Comment by transistive** [comment]
Sorry about that. I received to code from the issue on the client library! Thank you for the quick fix, as always :)

**Comment by in3rsha** [comment]
> Btw it's really dangerous piece of code. After it was working I reached a moment when my computer started freezing and Neo4j crashed at memory.

Sorry about that, I should have put in a break point when the array became large enough.

Thank you the fix. Been scratching my head over it for the last few days.

**Comment by stefanak-michal** [comment]
@transistive @in3rsha No big deal, no harm was done. 

Always happy to help.
