### ISSUE TITLE
v2.7 - Call to undefined method Bolt\Bolt::setScheme() with NoAuth (NEO4J_AUTH=none)

### ISSUE THREAD

**Issue by Mulkave** [neo4j-php/Bolt#66]
**Describe the bug**
Ran `composer update`, using [neo4j-php-client](https://github.com/neo4j-php/neo4j-php-client) upgraded Bolt to `2.7` which then broke queries with the following error:

```
PHP Error:  Call to undefined method Bolt\Bolt::setScheme() in /var/www/html/vendor/laudis/neo4j-php-client/src/Authentication/NoAuth.php on line 41
```

**To Reproduce**
Connect to Neo4j with Auth set to `none` (e.g. `NEO4J_AUTH=none`)

**Expected behavior**
Connection to be established successfully.

**Desktop (please complete the following information):**
 - OS: `MacOS 12.0.1`
 - PHP Version: `8.1.0`
 - Neo4j Version `4.4`
 - Bolt Library Version `v2.7` - ref: `a5d7a8e9a5073fa93f185621ff4e8a1c0ddab877`

**Additional context**
*N/A*

**Comment by stefanak-michal** [comment]
setScheme was removed due to implementation of Auth helper. Isn't needed anymore. I'll restore it for backward compatibility.

**Comment by stefanak-michal** [comment]
https://github.com/neo4j-php/Bolt/releases/tag/v2.7.1

**Comment by Mulkave** [comment]
That was quick! Thank you 😄
