### ISSUE TITLE
Enable SSL settings for Socket

### ISSUE THREAD

**Issue by transistive** [neo4j-php/Bolt#82]
**Is your feature request related to a problem? Please describe.**
I want to enable the Sockets extension if it is installed for the driver. The problem is that it does not have a `setSslContextOptions` function like the StreamSocket which means the speedup will be impossible for Aura users as I cannot enable SSL.

**Describe the solution you'd like**
I would love the same method `setSslContextOptions` on the Socket for feature parity. It might be best to include in the Interface. What do you think?

Kind regards,

Ghlen

**Comment by stefanak-michal** [comment]
From what I know php sockets extensions doesn't support SSL. That was a reason why StreamSocket connection class was created. 

Maybe there is a way I don't know about and I'm open for ideas.
